### ISSUE TITLE
抄袭！！！Fork别人的就好了，为什么要说成自己写的？拿别人的几个项目改一下，thanks一下就可以了？你做了什么？

### ISSUE THREAD

**Issue by lexluthors** [ImKarl/CharacterPickerView#18]
抄袭！！！Fork别人的就好了，为什么要说成自己写的？拿别人的几个项目改一下，thanks一下就可以了？你做了什么？封装一下？不错，拿了别人的，改个名字还是挺聪明的。类名都一样！

**Comment by ImKarl** [comment]
麻烦看下`ChangeLog`

**Comment by lexluthors** [comment]
我看ChangeLog有什么用？写个thanks就是自己的了？里面的类都是从那两个项目中复制过来的，别人的名字在项目中都没有！都是用的别人的代码。你为什么不fork就好了，非要写成自己的？那别人的项目改一下，这算什么？

**Comment by lexluthors** [comment]
你看清楚我项目中，和别人的方式一样不！要是不一样，你全家死光如何？敢不敢赌咒？通用操作类，方法大家都是一样的。这算抄袭？看清楚再喷！你这个就是照搬照抄了，真是有脸！

**Comment by ImKarl** [comment]
`方式不一样` 就是多拷贝份其他源码吗？你复制别人代码，有声明原作者吗？

**Comment by ImKarl** [comment]
我就是完全引入别人的源码，我从哪里拷贝的、做了什么改动，都有说明。
你能尊重下别人吗？

**Comment by lexluthors** [comment]
你仔细看清楚，我给你发的邮件，截图，我刚开始是发了原作者的源码地址的！你可以看git提交记录！我后来因为修改了，基本没用里面的代码，只是那个build模式是类似的。但是我的返回方式和他一样？我的线程处理和他一样？眼瞎了？

**Comment by lexluthors** [comment]
都是通用方法，里面我有一个逻辑操作方法是相同的吗？而且有很多方法都没用好吧

**Comment by ImKarl** [comment]
我从来没收到你的邮件，，既然你也承认是拿别人的开源项目改的，为什么不尊重下原作者？
代码倒是改得挺快，提个issues把对你有利的都留下，不利的全删了，可以的。

**Comment by lexluthors** [comment]
他妈的真是傻逼！谁告诉你拿别人项目改的？！你看过里面有哪些有用的方法，哪些没用的！？你的这个通知我邮箱回复不了，提示账号错误。你登陆你项目中留的邮箱！看看有没有！没有明天我从新发，反正都在我邮箱已发送中！或者你给我发个你常联系得号。我给你从新发！我不怕麻烦！有没有抄袭你看清楚再说！你代码中导入的别人源码，我暂且不说，你上面一个包中的逻辑代码中有一些方法网上抄的怎么说？！这是不是抄袭！？

**Comment by ImKarl** [comment]
山寨无罪，抄袭有理！
抄袭的都是大爷，开源协议都是摆设。
跟不讲理的人讲道理，是我的错。我也懒得说你了，你心安理得就行

**Comment by lexluthors** [comment]
什么垃圾玩意，自己看源码，看看里面什么是抄的！我要用他的方式去实现我还用自己建个项目？没看到我仓库也有fork！？跟傻逼我是说不通了！傻逼总认为一些通用方法都是抄的！傻逼的项目也有这些方法，也没声明！我就不能用build模式？！我根本懒得跟你说，不分青红皂白诬陷，放大！连看都不看里面怎么用的都开喷！不是脑残是什么？

**Comment by ImKarl** [comment]
总共才几个类，连原作者的注释还在，代码结构等就不用说了，连原作者名字都抄了…
那就不能在项目说明里  声明下原作者吗？
不一样的就是你说的导入份jni源码吗？
