### ISSUE TITLE
抄袭的！！！

### ISSUE THREAD

**Issue by lexluthors** [ImKarl/CharacterPickerView#19]
登录你163邮箱看看！明天我会从新给你发！诬陷老子，死你全家！

**Comment by lexluthors** [comment]
你看看你这有几个类？几个是你写的？自己没点数？我说了，那个build模式我从新写也是和那个一样的。你能写出花样是吧？我直接就用了，怎么了？不可以？注释写上去我擦掉再写一遍是吧？我改个注释就不是抄了是吧？行，要是这种sb的想法，我满足你。我明天改到注释，方法名字换一下，这样sb就不会像疯狗一样咬我了。难道别人用的build模式，我也用，就不行是吧？这种代码谁写都是类似的。你代码中要是有这种代码是不是也算抄袭？我要是真用了人家的核心代码，我也认了，你说什么我也不反驳。关键是我没用别人的核心算法。那些通用方法网上都有。也就你这种sb会说抄袭。

**Comment by ImKarl** [comment]
你是大爷，你说了算

**Comment by lexluthors** [comment]
我不是大爷，你这个抄袭的帽子扣的太大，我承担不起！你项目中很多都是网上抄的，而且没有写别人名字，这算不算抄？我要是真照搬的，我也认了，但是我用这个的时候还是eclipse的时候，都好早了，大概14年就用了，我现在只不过用as整理发出来，你就给扣个帽子抄袭。
